// Generated by CoffeeScript 1.3.1
(function() {
  var FlameApp, HEIGHT, WIDTH, n, palCol, palette, sd;

  WIDTH = 500;

  HEIGHT = 256;

  sd = [];

  window.sd = sd;

  palCol = function(intensity) {
    var b, g, r;
    r = Math.min(intensity, 85) * 3;
    intensity = Math.max(intensity - 85, 0);
    g = Math.min(intensity, 85) * 3;
    intensity = Math.max(intensity - 85, 0);
    b = Math.min(intensity, 85) * 3;
    return [r, g, b];
  };

  palette = (function() {
    var _i, _results;
    _results = [];
    for (n = _i = 0; _i <= 255; n = ++_i) {
      _results.push(palCol(n));
    }
    return _results;
  })();

  console.log('poo', palette);

  FlameApp = (function() {

    FlameApp.name = 'FlameApp';

    function FlameApp() {}

    FlameApp.prototype.main = function() {
      this.createCanvas();
      this.imageData = this.context.getImageData(0, 0, WIDTH, HEIGHT);
      this.buf = new ArrayBuffer(this.imageData.data.length);
      this.buf8 = new Uint8ClampedArray(this.buf);
      this.data = new Uint32Array(this.buf);
      return this.runLoop();
    };

    FlameApp.prototype.runLoop = function() {
      var _this = this;
      return setTimeout(function() {
        var col, myy, n, sc, x, y, _i, _j, _k, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
        _this.clearCanvas();
        sc = sd.slice(0);
        sc[0] || (sc[0] = []);
        for (n = _i = 0; _i <= 255; n = ++_i) {
          sc[0][Math.round(Math.random() * (WIDTH - 1))] = Math.round(Math.random() * 5000) + 500;
        }
        for (x = _j = 0, _ref = WIDTH - 1; 0 <= _ref ? _j <= _ref : _j >= _ref; x = 0 <= _ref ? ++_j : --_j) {
          for (y = _k = 1, _ref1 = HEIGHT - 1; 1 <= _ref1 ? _k <= _ref1 : _k >= _ref1; y = 1 <= _ref1 ? ++_k : --_k) {
            sc[y] || (sc[y] = []);
            sc[y][x] = ((((_ref2 = sc[y - 1]) != null ? _ref2[x - 1] : void 0) || 0) + (((_ref3 = sc[y - 1]) != null ? _ref3[x] : void 0) || 0) + (((_ref4 = sc[y - 1]) != null ? _ref4[x + 1] : void 0) || 0) + (((_ref5 = sc[y - 2]) != null ? _ref5[x] : void 0) || 0)) / 4.073;
            col = Math.round(sc[y][x] / 5000 * 255);
            if (col < 1) {
              col = 0;
            }
            if (col > 254) {
              col = 254;
            }
            myy = y + 1;
            _this.data[(HEIGHT - myy) * WIDTH + x] = (255 << 24) | (palette[col][2] << 16) | (palette[col][1] << 8) | palette[col][0];
          }
        }
        sd = sc.slice(0);
        _this.imageData.data.set(_this.buf8);
        _this.context.putImageData(_this.imageData, 0, 0);
        if (!_this.terminateRunLoop) {
          return _this.runLoop();
        }
      }, 30);
    };

    FlameApp.prototype.createCanvas = function() {
      this.canvas = document.getElementById('canvas');
      this.context = this.canvas.getContext('2d');
      this.canvas.width = WIDTH;
      return this.canvas.height = HEIGHT;
    };

    FlameApp.prototype.clearCanvas = function() {
      return this.context.clearRect(0, 0, this.canvas.width, this.canvas.height);
    };

    return FlameApp;

  })();

  window.flame = new FlameApp;

  window.flame.main();

}).call(this);
